/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package opi.rosokha.settings;

import javax.swing.JOptionPane;

/**
 *
 * @author Maksim
 */
public class Setting extends javax.swing.JInternalFrame {
    private static String[] sorting = {"Статичний елемент","Динамічний елемент","Силовий елемент"};

    /**
     * Creates new form Setting
     */
    public Setting() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlBackground = new javax.swing.JPanel();
        pnlSorting = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        chkbPowerElement = new javax.swing.JCheckBox();
        chkbDynamicElement = new javax.swing.JCheckBox();
        chkbStaticElements = new javax.swing.JCheckBox();
        lbl1 = new javax.swing.JLabel();
        btnSaveSettings = new javax.swing.JButton();

        setTitle("Налаштування");

        pnlBackground.setBackground(new java.awt.Color(126, 126, 126));

        pnlSorting.setBackground(new java.awt.Color(50, 51, 55));
        pnlSorting.setEnabled(false);
        pnlSorting.setVerifyInputWhenFocusTarget(false);

        jPanel1.setOpaque(false);

        chkbPowerElement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chkbPowerElement.setForeground(new java.awt.Color(255, 255, 255));
        chkbPowerElement.setSelected(true);
        chkbPowerElement.setText("Силові елементи");
        chkbPowerElement.setContentAreaFilled(false);

        chkbDynamicElement.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chkbDynamicElement.setForeground(new java.awt.Color(255, 255, 255));
        chkbDynamicElement.setSelected(true);
        chkbDynamicElement.setText("Динамічні елементи");
        chkbDynamicElement.setContentAreaFilled(false);

        chkbStaticElements.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        chkbStaticElements.setForeground(new java.awt.Color(255, 255, 255));
        chkbStaticElements.setSelected(true);
        chkbStaticElements.setText("Статичні елементи");
        chkbStaticElements.setContentAreaFilled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(chkbPowerElement)
                        .addComponent(chkbDynamicElement)
                        .addComponent(chkbStaticElements))
                    .addContainerGap(187, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(chkbStaticElements)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkbDynamicElement)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(chkbPowerElement)
                    .addContainerGap(14, Short.MAX_VALUE)))
        );

        lbl1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lbl1.setForeground(new java.awt.Color(255, 255, 255));
        lbl1.setText("Показувати тільки:");

        javax.swing.GroupLayout pnlSortingLayout = new javax.swing.GroupLayout(pnlSorting);
        pnlSorting.setLayout(pnlSortingLayout);
        pnlSortingLayout.setHorizontalGroup(
            pnlSortingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortingLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(lbl1)
                .addGap(99, 99, 99)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(85, Short.MAX_VALUE))
        );
        pnlSortingLayout.setVerticalGroup(
            pnlSortingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSortingLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, Short.MAX_VALUE)
                .addGap(15, 15, 15))
            .addGroup(pnlSortingLayout.createSequentialGroup()
                .addContainerGap(58, Short.MAX_VALUE)
                .addComponent(lbl1)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        btnSaveSettings.setBackground(new java.awt.Color(50, 51, 55));
        btnSaveSettings.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnSaveSettings.setForeground(new java.awt.Color(255, 255, 255));
        btnSaveSettings.setText("Зберегти налаштування");
        btnSaveSettings.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaveSettings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveSettingsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlSorting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(10, 10, 10))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSaveSettings)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlSorting, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 165, Short.MAX_VALUE)
                .addComponent(btnSaveSettings, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(100, 100, 100))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveSettingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveSettingsActionPerformed

        if(!chkbStaticElements.isSelected() && !chkbDynamicElement.isSelected() && !chkbPowerElement.isSelected()){
            sorting[0] = null; sorting[1] = null; sorting[2] = null;
        }
        if(!chkbStaticElements.isSelected() && !chkbDynamicElement.isSelected() && chkbPowerElement.isSelected()){
            sorting[0] = null; sorting[1] = null; sorting[2] = "Силовий елемент";
        }
        if(!chkbStaticElements.isSelected() && chkbDynamicElement.isSelected() && !chkbPowerElement.isSelected()){
            sorting[0] = null; sorting[1] = "Динамічний елемент"; sorting[2] = null;
        }
        if(!chkbStaticElements.isSelected() && chkbDynamicElement.isSelected() && chkbPowerElement.isSelected()){
            sorting[0] = null; sorting[1] = "Динамічний елемент"; sorting[2] = "Силовий елемент";
        }
        if(chkbStaticElements.isSelected() && !chkbDynamicElement.isSelected() && !chkbPowerElement.isSelected()){
            sorting[0] = "Статичний елемент"; sorting[1] = null; sorting[2] = null;
        }
        if(chkbStaticElements.isSelected() && !chkbDynamicElement.isSelected() && chkbPowerElement.isSelected()){
            sorting[0] = "Статичний елемент"; sorting[1] = null; sorting[2] = "Силовий елемент";
        }
        if(chkbStaticElements.isSelected() && chkbDynamicElement.isSelected() && !chkbPowerElement.isSelected()){
            sorting[0] = "Статичний елемент"; sorting[1] = "Динамічний елемент"; sorting[2] = null;
        }
        if(chkbStaticElements.isSelected() && chkbDynamicElement.isSelected() && chkbPowerElement.isSelected()){
            sorting[0] = "Статичний елемент"; sorting[1] = "Динамічний елемент"; sorting[2] = "Силовий елемент";
        }
        
        
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Налаштування збережено" ,"Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveSettingsActionPerformed
    
    public static String[] getSorting() {
        return sorting;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSaveSettings;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBox chkbDynamicElement;
    private javax.swing.JCheckBox chkbPowerElement;
    private javax.swing.JCheckBox chkbStaticElements;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel lbl1;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JPanel pnlSorting;
    // End of variables declaration//GEN-END:variables
}
