/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package opi.rosokha.elements;

import java.util.List;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import opi.rosokha.ConnectorWithDatabase;
import opi.rosokha.FrmMain;
import opi.rosokha.authorization.User;

/**
 *
 * @author Maksim
 */
public class Element extends javax.swing.JInternalFrame {

    private int id;
    private String name;
    private String type;
    private String description;
    
    private EditElement frmEditElement;
    private static FrmMain frmMain;
    
    /**
     * Creates new form Element
     */
    public Element(int id, String name, String type, String description) {
        initComponents();
        this.id = id;
        this.name = name;
        this.type = type;
        this.description = description;
        
        lblElementName.setText(name);
        lblElementType.setText(type);
        txtText.setText(description);
        
        checkUserStatus();
    }
    
    public void checkUserStatus(){
        if(FrmMain.getUser().getStatus().equals(User.ADMINISTRATOR)) {
            plnRegistredUser.setVisible(true);
            pnlAdministrator.setVisible(true);
            btnEdit.setVisible(true);
            btnDelete.setVisible(true);
            btnSave.setVisible(true);
        }else if(FrmMain.getUser().getStatus().equals(User.REGISTERED_USER)){
            plnRegistredUser.setVisible(true);
            btnEdit.setVisible(false);
            btnDelete.setVisible(false);
            btnSave.setVisible(true);
        }else{
            plnRegistredUser.setVisible(false);
            pnlAdministrator.setVisible(false);
            btnSave.setVisible(false);
        }
    }
    
    public void markCheckBoxes(){
        List<Element> favoriteElements = ConnectorWithDatabase.getListOfFavoriteElements();
        List<Element> studiedElements = ConnectorWithDatabase.getListOfStudiedElements();
        
        if(favoriteElements != null){
            for(Element element: favoriteElements){
                if(this.id == element.getId()){
                    ckbFovorites.setSelected(true);
                    break;
                } else {
                    ckbFovorites.setSelected(false);
                }
            }
        }
        
        if(studiedElements != null){
            for(Element element: studiedElements){
                if(id == element.getId()){
                    ckbStudied.setSelected(true);
                    break;
                }else {
                    ckbStudied.setSelected(false);
                }
            }
        }
    }
    

    public void setUserStatus(String userStatus) {
        FrmMain.getUser().setStatus(userStatus);
        checkUserStatus();
    }
    
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
        lblElementName.setText(name);
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
        lblElementType.setText(type);
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
        txtText.setText(description);
    }
    
    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
    
    public static void setFrmMain(FrmMain frmMain) {
        Element.frmMain = frmMain;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlBackground = new javax.swing.JPanel();
        lblElementName = new javax.swing.JLabel();
        lblElementType = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtText = new javax.swing.JTextArea();
        plnRegistredUser = new javax.swing.JPanel();
        ckbFovorites = new javax.swing.JCheckBox();
        ckbStudied = new javax.swing.JCheckBox();
        pnlAdministrator = new javax.swing.JPanel();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setTitle("Про елемент");

        pnlBackground.setBackground(new java.awt.Color(126, 126, 126));

        lblElementName.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblElementName.setForeground(new java.awt.Color(255, 204, 51));
        lblElementName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElementName.setText("Назва елементу");
        lblElementName.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        lblElementType.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblElementType.setForeground(new java.awt.Color(255, 255, 255));
        lblElementType.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblElementType.setText("Тип елементу");
        lblElementType.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        txtText.setEditable(false);
        txtText.setColumns(20);
        txtText.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtText.setLineWrap(true);
        txtText.setRows(5);
        txtText.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(txtText);

        plnRegistredUser.setOpaque(false);

        ckbFovorites.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbFovorites.setForeground(new java.awt.Color(255, 255, 255));
        ckbFovorites.setText("Вибрані");
        ckbFovorites.setOpaque(false);

        ckbStudied.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        ckbStudied.setForeground(new java.awt.Color(255, 255, 255));
        ckbStudied.setText("Вивчені");
        ckbStudied.setOpaque(false);

        javax.swing.GroupLayout plnRegistredUserLayout = new javax.swing.GroupLayout(plnRegistredUser);
        plnRegistredUser.setLayout(plnRegistredUserLayout);
        plnRegistredUserLayout.setHorizontalGroup(
            plnRegistredUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnRegistredUserLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(ckbFovorites, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(ckbStudied, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        plnRegistredUserLayout.setVerticalGroup(
            plnRegistredUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(plnRegistredUserLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(ckbFovorites)
                .addComponent(ckbStudied))
        );

        pnlAdministrator.setOpaque(false);

        btnEdit.setBackground(new java.awt.Color(0, 153, 255));
        btnEdit.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(255, 255, 255));
        btnEdit.setText("Змінити");
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelete.setBackground(new java.awt.Color(255, 0, 51));
        btnDelete.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnDelete.setForeground(new java.awt.Color(255, 255, 255));
        btnDelete.setText("Видалити");
        btnDelete.setBorderPainted(false);
        btnDelete.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdministratorLayout = new javax.swing.GroupLayout(pnlAdministrator);
        pnlAdministrator.setLayout(pnlAdministratorLayout);
        pnlAdministratorLayout.setHorizontalGroup(
            pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdministratorLayout.createSequentialGroup()
                .addComponent(btnEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(118, 118, 118))
        );
        pnlAdministratorLayout.setVerticalGroup(
            pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdministratorLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(pnlAdministratorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnDelete)))
        );

        btnSave.setBackground(new java.awt.Color(50, 51, 55));
        btnSave.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnSave.setForeground(new java.awt.Color(255, 255, 255));
        btnSave.setText("Зберегти зміни");
        btnSave.setBorderPainted(false);
        btnSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlBackgroundLayout = new javax.swing.GroupLayout(pnlBackground);
        pnlBackground.setLayout(pnlBackgroundLayout);
        pnlBackgroundLayout.setHorizontalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                        .addComponent(plnRegistredUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addComponent(pnlAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10))
            .addGroup(pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblElementName, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblElementType, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlBackgroundLayout.setVerticalGroup(
            pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlBackgroundLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblElementName)
                .addGap(8, 8, 8)
                .addComponent(lblElementType)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                .addGap(10, 10, 10)
                .addGroup(pnlBackgroundLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(plnRegistredUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pnlAdministrator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlBackground, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(ConnectorWithDatabase.deleteElement(this)){
            this.setVisible(false);
            showMessageDialog(null, "Елемент успішно видалений");
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        if(ckbFovorites.isSelected()){
            ConnectorWithDatabase.addElementToFavorites(this);
        } else {
            ConnectorWithDatabase.deleteElementFromFavorites(this);
        }
        
        if(ckbStudied.isSelected()){
            ConnectorWithDatabase.addElementToStudied(this);
        } else {
            ConnectorWithDatabase.deleteElementFromStudied(this);
        }
        
        this.setVisible(false);
        JOptionPane.showMessageDialog(null, "Налаштування збережено" ,"Success", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        this.setVisible(false);
        
        if(frmEditElement == null){
            frmEditElement = new EditElement(this);
            frmMain.getDesktopPane().add(frmEditElement);
            frmEditElement.setSize(frmMain.getDesktopPane().getWidth(), frmMain.getDesktopPane().getHeight());
        }
        frmEditElement.setComponents();
        frmEditElement.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnSave;
    private javax.swing.JCheckBox ckbFovorites;
    private javax.swing.JCheckBox ckbStudied;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblElementName;
    private javax.swing.JLabel lblElementType;
    private javax.swing.JPanel plnRegistredUser;
    private javax.swing.JPanel pnlAdministrator;
    private javax.swing.JPanel pnlBackground;
    private javax.swing.JTextArea txtText;
    // End of variables declaration//GEN-END:variables
}
